module.exports = {
	PARAM_MISSING: 422,
	PARAM_MISSING_MSG: 'Require parameter missing',
	NO_DATA: 400,
	NO_DATA_FOUND: 'No data found',
	NO_USER_FOUND: 'User not found',
	INVALID_USER: 'Not a valid user',
	USER_ALREADY_EXIST: 'User already exist with mobile or email',
	SUCCESS: 200,
	SUCCESS_MSG: 'Success',
	QUERY_ERROR: 500,
	QUERY_ERROR_MSG: 'Something Went wrong',
	INVALID_CREDENTIAL: 401,
	INVALID_CREDENTIAL_MSG: 'Invalid credential. Please try again.',
	UNAUTHORIZE: 401,
	UNAUTHORIZE_MSG: 'Unauthorize User',
	BAD_REQUEST: 400,
	BAD_REQUEST_MSG: 'Entered data is Invalid',
	INCORRECT_EMAIL: 'Incorrect email',
	INCORRECT_PASSWORD: 'Incorrect current password',
	INCORRECT_MOBILE: 'Incorrect mobile',
	INCORRECT_OTP: 'Incorrect otp',
	EMAIL_NOT_INVITED:
		'This email is not invited, Please enter the valid email',
	INVITATION_ALREADY_ACCEPTED: `You've already created your account with this email`,
	EXPIRED_LINK: 'Link has been expired',
	INVALID_LINK: 'Invalid link',
	UNVERIFIED_EMAIL: 'Email is not verified',
	UNVERIFIED_MOBILE: 'Mobile is not verified',
	BLOCKED_USER: 'Your account has been blocked by the Admin',

	RESET_PASSWORD_MOBILE: 'Otp has been sent to you mobile',
	RESET_PASSWORD_EMAIL: 'Reset link has been send to your registered email ',
	OTP_SEND_MOBILE: 'Otp has been sent to your registered mobile',
	OTP_SEND_EMAIL: 'Otp has been sent to your registered email',
	DELETE_ACCOUNT: 'Your account has been deleted successfully',
	ADMIN_LOGIN_ERROR: 'The email address and password do not match',
	COMP_NOT_FOUND: 'Comp not found, please check',
	EDIT_COMP: `Comp has been updated successfully`,
	INVALID_TRADE_REQUEST: 'Invalid trade request',
	TRADE_ACTION_TAKEN:
		'You can not update this trade because action has been already taken on this',
	NOT_COUNTER_TRADE: 'You can not counter this type of trade request',

	LEASE_FOUND_WITH_DIFFERENT_OWNER: `We found another comp with same address, size and commencement.`,
	LEASE_FOUND_WITH_SAME_OWNER: `You already have a comp with same address, size and commencement. To continue, change any of the parameter.`,

	SALE_FOUND_WITH_DIFFERENT_OWNER: `We found another comp with same address, close of escrow date and sale price.`,
	SALE_FOUND_WITH_SAME_OWNER: `You already have a comp with same address, close of escrow date and sale price.
	To continue, change any of the parameter.`,
	COMP_SHARE: 'You have shared the comp',
	NOT_EDITOR: 'You do not have a permission to edit this comp',
	CAN_NOT_REMOVE_OWNER: 'You are not allowed to edit the owner',
	CAN_NOT_EDIT_OTHER_SIDE:
		'You are not allowed to edit the other side editor',
	ALREADY_REPORTED: 'Action has been already taken on this changes',
	CHANGES_NOT_FOUND: 'Changes not found with this field',
	BLOCKED: 'Broker has been blocked successfully',
	UNBLOCKED: 'Broker has been unblocked successfully',
	ACTIVATE_COMP: 'Comp status changed to Active',
	IN_ACTIVATE_COMP: 'Comp status changed to InActive',
	VERIFY_BROKER: 'Broker has been verified successfully',
	REJECT_BROKER: 'Broker has been rejected',
	CAN_NOT_DELETE_COMP: 'You do not have a permission to delete this comp',
	DELETE_COMP_LOCKED: 'Locked comp can not be deleted',
	COMP_FORBIDDEN: 'You are not allowed to access this comp',
	SEND_NOTIFICATION: 'Notification  sent successfully!',
	REQUEST_ADDED: 'Request has been sent',
	TRADE_REQUEST_UPDATED: 'Trade request has been updated successfully',
	ACCEPT_REQUEST: 'Trade request has been accepted successfully',
	REJECT_REQUEST: 'Request has been rejected.',

	NOT_ALLOWED_TRADE: `You're not allowed to take action on this trade`,
	TRADE_EXISTS: `You have already requested this comp with this broker`,
	DELETE_REQUEST: 'Request has been deleted',
	TRADE_NOT_FOUND: 'Trade not found, please check',
	ACTION_TAKEN: 'Action has been already taken on this request',
	CANCEL_NOT_ALLOWED: 'You are not allowed to cancel this request',
	INVITE_MSG: 'An invitation has been sent',

	COMP_ADD_FAVORITE: 'Comp has been added to favorites',
	COMP_REMOVE_FAVORITE: 'Comp has been removed from favorites',
	BROKER_ADD_FAVORITE: 'Broker has been added to favorites',
	BROKER_REMOVE_FAVORITE: 'Broker has been removed from favorites',
	NOTIFICATION_DELETE: 'Notification has been deleted',
	NOTIFICATION_DELETE_ALL: 'Notification has been deleted',
	APPROVAL_NOT_ALLOWED: `You're not allowed to approve this comp`,
	COMP_APPROVED: `You have approved the comp level to gold`,
	EDIT_COMP_LOCKED: `Comp has been locked, You're not allowed to edit`,

	SET_BROKER_APPROVAL: 'Approval status has been changed',
	DELETE_DEVICE_TOKEN: 'Device token has been removed',

	CHANGE_PASSWORD: 'Your password has been updated successfully!',

	REJECT_TRADE_ON_BROKER_EDIT: 'is no longer a broker in the comp',
	REJECT_TRADE_ON_COMP_DELETE:
		'Comp is no longer exists, Editor brokers has deleted the comp',
	REJECT_TRADE_ON_COMP_CONFIDENTIAL:
		'Editor broker made the comp confidential',

	DELETE_COMP_MSG: 'Comp no longer exists!',
	BROKER_EDIT_MSG: 'You are no longer part of this comp!',
	INVITATION_ACCEPTED: 'Invitation accepted!',
	PASSWORD_UPDATED: 'Password Updated!',
	SHARED_COMP: 'A comp has been shared with you!',
	GOLD_ACHIEVED: 'Gold level achieved!',
	COMP_LOCKED_MSG: 'Comp is now locked!',
	LEASE_EXPIRY_MSG: 'Your lease will expire!',
	CHANGE_APPROVED: 'Change Approved!',
	CHANGE_REJECTED: 'Change Rejected!',
	CHANGE_COUNTERED: 'Change countered!',
	BROKER_ADDED_IN_COMP: 'You have received a new comp!',
	EDITOR_ADDED_IN_COMP: 'You have been added as an editor!',
	APPROVAL_NEEDED: 'Approval needed!',
	REQUEST_ACCEPTED: 'Request Accepted!',
	REQUEST_REJECTED: 'Request Rejected!',
	TRADE_REQUEST_ACCEPTED: 'Trade Request Accepted!',
	TRADE_REQUEST_REJECTED: 'Trade Request Rejected!',
	TRADE_REQUEST_COUNTERED: 'Trade Request Countered!',
	EDIT_COMP_TITLE: 'Comp changed!',
	EDIT_COMP_CONFIDENTIAL: `You can not edit traded comp to confidential`,
	DELETE_TRADED_COMP: 'You can not delete traded comp',
	NORMAL_REQUEST: 'New Comp Request!',
	TRADE_REQUEST: 'New Trade Request!',
	INACTIVE_BROKER_MSG: 'Inactive editor broker found!',
	ALREADY_TRADED: 'The broker has already received this comp!',
	EMAIL_EXIST:
		'This broker is already on the platform, please use another email address',
	MOBILE_EXIST:
		'This broker is already on the platform, please use another mobile number',
	PLAN_EXIST: 'Plan already exist',
	PLAN_NOT_FOUND: 'Plan not found',
	PLAN_ADDED: 'Subscription plan has been added',
	PLAN_UPDATED: 'Subscription plan has been updated',
	PLAN_DELETED: 'Subscription plan has been deleted',
	COUPON_EXIST: 'Coupon already exist',
	COUPON_SHARED: 'Coupon has been shared with the users',
};
